### ISSUE TITLE
Как удалить?

### ISSUE THREAD

**Issue by Hope1esss** [FlimixST/DiscordFix#1]
Даже после сноса app.asar работает туннелирование по всей системе, и дискорд теперь не работает с впном, который я включаю самостоятельно

**Comment by Hope1esss** [comment]
Так мужик, я разобрался, тебе стоит написать принцип работы и как включать/выключать твой amnezia warp, потому что на данный момент вообще не прозрачно для обычного пользователя что происходит.

**Comment by FlimixST** [comment]
Я реализовал его через portable версию AmneziaWG, чтобы выключить просто надо закрыть через диспетчер задач

**Comment by Hope1esss** [comment]
Используется обычный WARP конфиг с пулом айпишников, я правильно понял?

**Comment by FlimixST** [comment]
Да, встроил уже всё готовое чтобы человек просто скачал подтвердил и всё, а то в многих гайдах, зайди туда, зайди суда, скачай это и т.п, а тут просто 1 файлик поменять
