### ISSUE TITLE
ошибка

### ISSUE THREAD

**Issue by Bogdan451** [FlimixST/DiscordFix#3]
Скачал батник, запустил от имени администратора, выбрал первый пункт(дискорд был открыт), он закрылся, как и написало в cmd, дальше мне предложило установить новый азар, удалив старый, я нажал да, но затем прождав в районе секунды, выписалась красная надпись и через долю секунды закрылся cmd, при этом не успел прочесть ошибку или нет. Попытался открыть дискорд после этого, но он не запускался
![Снимок экрана 2024-11-07 171336](https://github.com/user-attachments/assets/a8ce9ef2-2d66-4ad7-9598-36a4bce2a3db)
тут я вписал "y", и произошло вышеперечисленное

**Comment by karpsik** [comment]
+

**Comment by Bogdan451** [comment]
> 

а-а, что такое?

**Comment by FlimixST** [comment]
> Скачал батник, запустил от имени администратора, выбрал первый пункт(дискорд был открыт), он закрылся, как и написало в cmd, дальше мне предложило установить новый азар, удалив старый, я нажал да, но затем прождав в районе секунды, выписалась красная надпись и через долю секунды закрылся cmd, при этом не успел прочесть ошибку или нет. Попытался открыть дискорд после этого, но он не запускался ![Снимок экрана 2024-11-07 171336](https://private-user-images.githubusercontent.com/108608961/383995389-a8ce9ef2-2d66-4ad7-9598-36a4bce2a3db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwMjMzMDAsIm5iZiI6MTczMTAyMzAwMCwicGF0aCI6Ii8xMDg2MDg5NjEvMzgzOTk1Mzg5LWE4Y2U5ZWYyLTJkNjYtNGFkNy05NTk4LTM2YTRiY2UyYTNkYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwN1QyMzQzMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZTNlNmJhMGY4M2Y5OGU0NGY3ZTFlZmU3MTQ0Zjc2YmZhZTFlMjllNmNiNWQ0MTFkYWY2ZmQ2NzI0ZjQyMTQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.MP3CvqK55uC4rmMKGrG15YNzHahe7woWV6KSGCLhztM) тут я вписал "y", и произошло вышеперечисленное

Странно что у тебя вообще попросило какое-либо подтверждение, лично у меня/моих друзей такого не было, попытайся опять его запустить и на видео это запиши, т.к если опять такое повторится, я понимал в чем проблема

**Comment by Bogdan451** [comment]
Мне удалось пофиксить. Скорее всего ошибка была вызвана тем что, у меня был скачан vencord, и из-за этого в cmd вылезала ошибка, но я сейчас накатил ваш батник на свеже-установленный дс, и все получилось
